In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [ ]:
arr1 = np.array(my_list)
arr1

array([1, 2, 3])

In [ ]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
#0 to 10 values incremented by 1
new_list = np.arange(0,10,1)
new_list

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Array of zeroes
np.zeros(3)

array([0., 0., 0.])

In [ ]:
#Matrix of zeroes by giving it as tuple
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
#Array of ones
np.ones(3)

array([1., 1., 1.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#gives array with values from 0 to 9 divided to 4 equal parts
np.linspace(0,9,4)

array([0., 3., 6., 9.])

In [ ]:
# Identity matrix of given dimension
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Random functions

In [ ]:
np.random.rand(5)

array([0.65395541, 0.10060983, 0.87571033, 0.03507313, 0.44260204])

In [ ]:
np.random.rand(3,3)

array([[0.2360389 , 0.58798893, 0.2783154 ],
       [0.03773473, 0.82021212, 0.69285946],
       [0.73614217, 0.52464496, 0.47511026]])

In [ ]:
np.random.randn(5)

array([ 1.29898781,  0.22834609, -1.12101226,  1.71278563,  0.10278062])

In [ ]:
np.random.randn(3,3)

array([[-0.47409535, -0.65264753,  0.70191204],
       [ 1.03032078,  0.71838003,  1.69169715],
       [-0.89539964,  1.50085959,  0.33787401]])

In [ ]:
#Any random number between 0 and 100 
np.random.randint(1,100)

47

In [ ]:
#given number of random numbers btw 2 numbers
np.random.randint(1,100,10)

array([53, 46, 11, 58, 38, 84, 17, 34, 22, 65])

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0,50,10)
ranarr

array([25,  8, 23, 49,  2, 29, 43,  3, 15,  5])

In [ ]:
#reshape can be used to change dimension of array
#if r*c is number of elements in array there will be no error
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

max,min

In [ ]:
ranarr.min()

2

In [ ]:
ranarr.max()

49

In [ ]:
ranarr

array([25,  8, 23, 49,  2, 29, 43,  3, 15,  5])

argmax and argmin return index of max and min value in array

In [ ]:
ranarr.argmax()

3

In [ ]:
ranarr.argmin()

4

Find shape of array

In [ ]:
arr.shape

(25,)

Find datatype in array

In [ ]:
arr.dtype

dtype('int64')

If we donot want to type np.random.randint we can use following method


In [ ]:
from numpy.random import randint
randint(2,10)

2