In [1]:
import numpy as np

In [4]:
arr = np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

Sliced notations

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[2:]
#array from 2 till end

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr[:6]
#this is same as arr[0:6]

array([0, 1, 2, 3, 4, 5])

In [11]:
arr[0:5] = 100
arr
#single value can be broadcasted to multiple postions

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [12]:
#Restoring arr back to as it was
arr = np.arange(0,11)
arr

In [13]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [14]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [16]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Here both slice_of_arr and arr value from 0 to 5 gets changed to 99. This is because it copies memory reference. To get a copy we can do as below. 

In [17]:
arr_copy = arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [21]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Here we can see that the original array's value is not affected

Indexing 2D array

In [25]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

Indexing digit 5

In [28]:
#position will be row * column
#Double bracket notation
arr_2d[0][0]

5

In [29]:
#single bracket notation to index 30
arr_2d[1,2]

30

Grabbing sections of matrix using sliced notation

In [30]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [35]:
#To retrieve 20 to 45
arr_2d[1:,:]

array([[20, 25, 30],
       [35, 40, 45]])

Conditional Selection

In [36]:
arr1 = np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
bool_arr = arr1 > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [39]:
arr1[bool_arr]

array([ 6,  7,  8,  9, 10])

In [41]:
#The above statement can be simplified as
arr1[arr1>5]

array([ 6,  7,  8,  9, 10])

In [42]:
arr1[arr1<3]

array([1, 2])

In [43]:
#Exercise to find sectins from 2d matrix
arr2d = np.arange(50).reshape(5,10)
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [44]:
#displaying 13,14,23,24
arr2d[1:3,3:5]

array([[13, 14],
       [23, 24]])